import { useEffect, useState } from 'react'
import { ClipboardList, Eye, Plus, Tags, X } from 'lucide-react'
import { apiService } from '../services/apiService'

const DetalleVenta = ({ venta, cerrar }) => <div className="fixed inset-0 z-60"><button onClick={cerrar} className="absolute inset-0 bg-rose-950/30" /><aside className="absolute right-0 top-0 h-full w-full max-w-sm bg-white shadow-2xl p-6"><button onClick={cerrar} className="float-right text-rose-800"><X /></button><h2 className="text-2xl font-extrabold text-rose-950">Venta #{venta.id}</h2><p className="mt-1 text-sm text-rose-700">Cliente: {venta.cliente?.nombre || venta.cliente?.email || 'No disponible'}</p><div className="mt-6 space-y-3">{(venta.detalles || []).map((detalle) => <div key={detalle.id || detalle.producto?.id} className="flex justify-between border-b border-rose-100 pb-3"><span className="text-rose-950">{detalle.producto?.nombre || `Producto #${detalle.producto?.id}`} × {detalle.cantidad}</span><strong className="text-amber-800">${Number(detalle.subtotal || detalle.precioUnitario * detalle.cantidad || 0).toLocaleString('es-MX', { minimumFractionDigits: 2 })}</strong></div>)}</div><div className="mt-6 pt-4 border-t border-rose-100 flex justify-between font-extrabold text-rose-950"><span>Total</span><span>${Number(venta.total || 0).toLocaleString('es-MX', { minimumFractionDigits: 2 })} MXN</span></div></aside></div>

export const AdminConsulta = ({ user, tipo, setVistaActual }) => {
  const [datos, setDatos] = useState([]); const [error, setError] = useState(''); const [nombre, setNombre] = useState(''); const [guardando, setGuardando] = useState(false); const [seleccionada, setSeleccionada] = useState(null)
  const esCategorias = tipo === 'categorias'
  const cargar = async () => { try { const respuesta = esCategorias ? await apiService.getCategorias() : await apiService.getVentas(); setDatos(Array.isArray(respuesta) ? respuesta : respuesta?.content || []) } catch (err) { setError(err.message || 'No se pudo cargar la información.') } }
  useEffect(() => { cargar() }, [esCategorias])
  if (user?.role !== 'ROLE_ADMIN') return <div className="max-w-4xl mx-auto px-4 py-12 text-center text-rose-900">Esta vista es exclusiva para administradores.</div>
  const guardarCategoria = async (evento) => { evento.preventDefault(); if (!nombre.trim()) return; setGuardando(true); setError(''); try { await apiService.crearCategoria({ nombre: nombre.trim() }); setNombre(''); await cargar() } catch (err) { setError(err.message || 'No se pudo guardar la categoría.') } finally { setGuardando(false) } }
  const Icono = esCategorias ? Tags : ClipboardList; const titulo = esCategorias ? 'Categorías' : 'Ventas realizadas'
  return <div className="max-w-5xl mx-auto px-4 py-10"><div className="bg-white rounded-3xl border border-rose-100 shadow-sm overflow-hidden"><header className="bg-rose-950 text-amber-100 p-6 flex items-center gap-3"><Icono className="text-amber-300" /><h1 className="text-xl font-extrabold">{titulo}</h1></header><div className="p-6">{esCategorias && <form onSubmit={guardarCategoria} className="flex gap-3 mb-6"><input value={nombre} onChange={(e) => setNombre(e.target.value)} placeholder="Nueva categoría" className="grow p-3 rounded-xl border border-rose-200 focus:outline-none focus:ring-2 focus:ring-amber-500" /><button disabled={guardando} className="inline-flex items-center gap-2 px-4 rounded-xl bg-amber-700 hover:bg-amber-600 disabled:bg-rose-200 text-white font-bold"><Plus className="w-4 h-4" />Agregar</button></form>}{error && <p className="text-rose-700 mb-4">{error}</p>}{!error && datos.length === 0 && <p className="text-rose-700">No hay registros todavía.</p>}{datos.map((dato) => <div key={dato.id} className="border-b border-rose-100 py-3 text-rose-950 flex items-center justify-between"><div><strong>{esCategorias ? dato.nombre : `Venta #${dato.id}`}</strong>{!esCategorias && <p className="text-sm text-rose-700">{dato.cliente?.nombre || dato.cliente?.email || 'Cliente'} · ${Number(dato.total || 0).toLocaleString('es-MX', { minimumFractionDigits: 2 })}</p>}</div>{!esCategorias && <button onClick={() => setSeleccionada(dato)} className="p-2 rounded-lg text-amber-800 hover:bg-amber-100" title="Ver detalle"><Eye className="w-5 h-5" /></button>}</div>)}<button onClick={() => setVistaActual('admin-panel')} className="mt-6 px-4 py-2 rounded-xl bg-amber-700 text-white font-bold">Volver al panel</button></div></div>{seleccionada && <DetalleVenta venta={seleccionada} cerrar={() => setSeleccionada(null)} />}</div>
}
