import { useEffect, useState } from 'react'
import { Building2, Eye, Mail, Phone, UserRound, X } from 'lucide-react'
import { apiService } from '../services/apiService'

export const AdminProveedores = ({ user, setVistaActual }) => {
  const [proveedores,setProveedores]=useState([]),[seleccionado,setSeleccionado]=useState(null),[error,setError]=useState('')
  useEffect(()=>{apiService.getProveedores().then(d=>setProveedores(Array.isArray(d)?d:[])).catch(e=>setError(e.message||'No se pudieron cargar proveedores.'))},[])
  if(user?.role!=='ROLE_ADMIN') return null
  return <div className="max-w-6xl mx-auto px-4 py-10"><section className="rounded-3xl p-7 text-white bg-gradient-to-r from-rose-950 via-amber-900 to-amber-600"><div className="flex gap-2 items-center text-amber-100"><Building2/><span className="text-sm font-bold uppercase">Administración</span></div><h1 className="mt-3 text-3xl font-extrabold">Proveedores</h1><p className="mt-2 text-amber-100">Consulta los proveedores registrados en el catálogo.</p></section>{error&&<p className="mt-5 text-red-600">{error}</p>}<div className="mt-7 grid md:grid-cols-2 gap-5">{proveedores.map(p=><article key={p.id} className="bg-white border border-rose-100 rounded-2xl shadow-sm p-5 flex items-center gap-4"><div className="w-12 h-12 rounded-full bg-amber-100 text-amber-800 grid place-items-center"><Building2/></div><div className="grow"><h2 className="font-bold text-rose-950">{p.nombre}</h2><p className="text-sm text-rose-700">{p.contacto}</p></div><button onClick={()=>setSeleccionado(p)} className="px-4 py-2 rounded-xl bg-amber-700 text-white font-bold inline-flex gap-2"><Eye className="w-4"/>Ver</button></article>)}</div><button onClick={()=>setVistaActual('admin-panel')} className="mt-7 px-5 py-3 rounded-xl bg-rose-950 text-white font-bold">Volver</button>{seleccionado&&<div className="fixed inset-0 z-60"><button onClick={()=>setSeleccionado(null)} className="absolute inset-0 bg-black/30"/><aside className="absolute right-0 top-0 h-full w-full max-w-md bg-white p-6 shadow-2xl"><button onClick={()=>setSeleccionado(null)} className="float-right"><X/></button><Building2 className="w-10 h-10 text-amber-700"/><h2 className="mt-4 text-2xl font-extrabold text-rose-950">{seleccionado.nombre}</h2><p className="mt-6 flex gap-3"><UserRound className="text-amber-700"/>{seleccionado.contacto}</p><p className="mt-4 flex gap-3"><Mail className="text-amber-700"/>{seleccionado.email}</p><p className="mt-4 flex gap-3"><Phone className="text-amber-700"/>{seleccionado.telefono}</p></aside></div>}</div>
}
