import { useEffect, useState } from 'react'
import { Eye, ReceiptText, X } from 'lucide-react'
import { apiService } from '../services/apiService'

const DetalleCompra = ({ compra, cerrar }) => <div className="fixed inset-0 z-60"><button onClick={cerrar} className="absolute inset-0 bg-rose-950/30" /><aside className="absolute right-0 top-0 h-full w-full max-w-sm bg-white shadow-2xl p-6"><button onClick={cerrar} className="float-right text-rose-800"><X /></button><h2 className="text-2xl font-extrabold text-rose-950">Compra #{compra.id}</h2><p className="mt-1 text-sm text-rose-700">{compra.fecha ? new Date(compra.fecha).toLocaleString('es-MX') : 'Fecha no disponible'}</p><div className="mt-6 space-y-3">{(compra.detalles || []).map((detalle) => <div key={detalle.id || detalle.producto?.id} className="flex justify-between border-b border-rose-100 pb-3"><span className="text-rose-950">{detalle.producto?.nombre || `Producto #${detalle.producto?.id}`} × {detalle.cantidad}</span><strong className="text-amber-800">${Number(detalle.subtotal || detalle.precioUnitario * detalle.cantidad || 0).toLocaleString('es-MX', { minimumFractionDigits: 2 })}</strong></div>)}{!compra.detalles?.length && <p className="text-rose-700">Sin detalle disponible.</p>}</div><div className="mt-6 pt-4 border-t border-rose-100 flex justify-between font-extrabold text-rose-950"><span>Total</span><span>${Number(compra.total || 0).toLocaleString('es-MX', { minimumFractionDigits: 2 })} MXN</span></div></aside></div>

export const MisCompras = ({ user, setVistaActual }) => {
  const [compras, setCompras] = useState([]); const [error, setError] = useState(''); const [seleccionada, setSeleccionada] = useState(null)
  useEffect(() => { apiService.getVentas().then((ventas) => setCompras((Array.isArray(ventas) ? ventas : []).filter((venta) => venta.cliente?.email === user?.username))).catch((err) => setError(err.message || 'No se pudieron cargar las compras.')) }, [user?.username])
  if (user?.role !== 'ROLE_CLIENTE') return <div className="max-w-5xl mx-auto px-4 py-12 text-center text-rose-900">Esta vista es exclusiva para clientes.</div>
  return <div className="max-w-4xl mx-auto px-4 py-10"><div className="bg-white rounded-3xl border border-rose-100 overflow-hidden shadow-sm"><header className="bg-rose-950 text-amber-100 p-6 flex items-center gap-3"><ReceiptText className="text-amber-300" /><div><h1 className="font-extrabold text-xl">Mis compras</h1><p className="text-sm text-amber-200">Historial de órdenes realizadas.</p></div></header><div className="p-6">{error && <p className="text-rose-700">{error}</p>}{!error && compras.length === 0 && <p className="text-rose-700">Aún no tienes compras registradas.</p>}{compras.map((compra) => <article key={compra.id} className="border-b border-rose-100 py-4 flex items-center justify-between gap-4"><div><p className="font-bold text-rose-950">Compra #{compra.id}</p><p className="text-sm text-rose-700">{compra.fecha ? new Date(compra.fecha).toLocaleString('es-MX') : 'Fecha no disponible'}</p></div><div className="flex items-center gap-4"><div className="text-right"><p className="font-bold text-amber-800">${Number(compra.total || 0).toLocaleString('es-MX', { minimumFractionDigits: 2 })} MXN</p><p className={`text-xs font-bold ${compra.estadoPago === 'PAGADO' ? 'text-green-600' : 'text-amber-700'}`}>{compra.estadoPago || 'PENDIENTE'}</p></div><button onClick={() => setSeleccionada(compra)} className="p-2 rounded-lg text-amber-800 hover:bg-amber-100" title="Ver detalle"><Eye className="w-5 h-5" /></button></div></article>)}<button onClick={() => setVistaActual('catalogo')} className="mt-6 px-4 py-2 rounded-xl bg-amber-700 text-white font-bold">Volver al catálogo</button></div></div>{seleccionada && <DetalleCompra compra={seleccionada} cerrar={() => setSeleccionada(null)} />}</div>
}
